### ISSUE TITLE
Completion not showing 

### ISSUE THREAD

**Issue by m1kuwu** [7HR4IZ3/acode-language-servers#4]
Android 13
Acode latest beta version

Logs: 
```Connected` to client: python                                       Sending: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"documentFormattingProvider":true,"documentHighlightProvider":true,"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"definitionProvider":true,"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"renameProvider":true,"foldingRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","="]},"textDocumentSync":{"change":2,"save":{"includeText":true},"openClose":true},"notebookDocumentSync":{"notebookSelector":[{"cells":[{"language":"python"}]}]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":{}},"serverInfo":{"name":"pylsp","version":"1.9.0"}}}                                                          Sending: {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"\/sdcard\/Code\/Python\/main.py","diagnostics":[]}}                                                            Sending: {"jsonrpc":"2.0","id":1,"result":null}                   Sending: {"jsonrpc":"2.0","id":2,"result":[]}                     Sending: {"jsonrpc":"2.0","id":3,"result":null}                   Sending: {"jsonrpc":"2.0","id":4,"result":[]}                     Sending: {"jsonrpc":"2.0","id":5,"result":null}                   Sending: {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"\/sdcard\/Code\/Python\/main.py","diagnostics":[]}}                                                            Sending: {"jsonrpc":"2.0","id":6,"result":[]}                     Sending: {"jsonrpc":"2.0","id":7,"result":null}                   Sending: {"jsonrpc":"2.0","method":"textDocument\/publishDiagnostics","params":{"uri":"\/sdcard\/Code\/Python\/main.py","diagnostics":[]}}```

**Comment by 7HR4IZ3** [comment]
Hi

Sometimes it takes time to show completions.. Don't know why though..

But I'll try to optimise it by the next update..

Tag me in a message to the Acode Telegram group, I just tried it now and it shows completions, I want to see the code you are trying it on and what is shows in the console (Acode console)

**Comment by 7HR4IZ3** [comment]
Tag me in a message to the Acode Telegram group, I just tried it now and it shows completions, I want to see the code ypu are trying it on and what is shows in the console (Acode console)
