### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by YZFloppa** [7HR4IZ3/acode-language-servers#5]
Hello i would like to ask can you add Lua support to the plugin?

**Comment by 7HR4IZ3** [comment]
Alright.. I'll add it soon.. But currently Lua is supported but only error reporting.

**Comment by YZFloppa** [comment]
> Alright.. I'll add it soon.. But currently Lua is supported but only error reporting.

I have to start a server for Lua right?

**Comment by 7HR4IZ3** [comment]
You just need to install the 'Lua Language Support' plugin and 'lua-language-server' in termux.

Already done with the plugin just fixing some bugs..
![Screenshot_2024-02-23-22-08-36-120_com foxdebug acode](https://github.com/7HR4IZ3/acode-language-servers/assets/90985774/7ec94a50-f060-4fc9-a9b0-a9a0a6142a0c)

**Comment by YZFloppa** [comment]
> You just need to install the 'Lua Language Support' plugin and 'lua-language-server' in termux.
> 
> Already done with the plugin just fixing some bugs.. ![Screenshot_2024-02-23-22-08-36-120_com foxdebug acode](https://private-user-images.githubusercontent.com/90985774/307454316-7ec94a50-f060-4fc9-a9b0-a9a0a6142a0c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjU2NjIsIm5iZiI6MTcwODcyNTM2MiwicGF0aCI6Ii85MDk4NTc3NC8zMDc0NTQzMTYtN2VjOTRhNTAtZjA2MC00ZmM5LWE5YjAtYTlhMGE2MTQyYTBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIxNTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZmU4MmQ4NTk2NzJlZDFiNmE1OGE1ZWEwNjg1OGUzNmE3NzI5MmNhNDFiNDFhY2VlZDcwNjBhZDZlYjVjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zj08rywVXEBc2Yd7wnBXVK3rzcHEFgZnn-Uup5eH-m4)

Can you make a full tutorial how to install the server after done making lua support i am kinda confused i tried to do the same thing in the guide but it keeps error

**Comment by 7HR4IZ3** [comment]
Alright.. When i'm done with the plugin i'll do so..
